#!/bin/bash

echo "=== WireGuard Client Configuration Check ==="
echo ""

# Get server public IP
PUBLIC_IP=$(curl -s http://checkip.amazonaws.com 2>/dev/null || echo "YOUR_SERVER_IP")

echo "📋 Correct WireGuard Client Configuration:"
echo ""
echo "[Interface]"
echo "PrivateKey = YOUR_PRIVATE_KEY_FROM_QR_CODE"
echo "Address = 10.8.0.2/24"  # or whatever IP assigned by WG-Easy
echo "DNS = 1.1.1.1, 8.8.8.8"
echo ""
echo "[Peer]"
echo "PublicKey = YOUR_SERVER_PUBLIC_KEY_FROM_QR_CODE"
echo "Endpoint = $PUBLIC_IP:51820"
echo "AllowedIPs = 0.0.0.0/0"  # This routes ALL traffic through VPN
echo "PersistentKeepalive = 25"
echo ""

echo "🔍 Common Client Configuration Issues:"
echo ""
echo "❌ Wrong Endpoint IP:"
echo "   - Should be: $PUBLIC_IP:51820"
echo "   - NOT: localhost, 127.0.0.1, or internal IP"
echo ""
echo "❌ Wrong AllowedIPs:"
echo "   - For full VPN: 0.0.0.0/0"
echo "   - For split tunnel: specific subnets only"
echo ""
echo "❌ Missing DNS:"
echo "   - Should have: DNS = 1.1.1.1, 8.8.8.8"
echo "   - Without DNS, websites won't resolve"
echo ""
echo "❌ Firewall blocking:"
echo "   - Client firewall may block WireGuard"
echo "   - Allow WireGuard app through firewall"
echo ""

echo "🧪 Testing Commands (run on client after connecting):"
echo ""
echo "# Test basic connectivity:"
echo "ping 8.8.8.8"
echo ""
echo "# Test DNS resolution:"
echo "nslookup google.com"
echo ""
echo "# Check your external IP (should be server IP):"
echo "curl https://httpbin.org/ip"
echo ""
echo "# Test website access:"
echo "curl -I https://google.com"
echo ""

echo "📱 Mobile App Settings:"
echo ""
echo "✅ Use 'Add Tunnel' -> 'Scan QR Code'"
echo "✅ Enable 'On-demand activation' if desired"
echo "✅ Check 'Allow access to local network' if needed"
echo ""

echo "🖥️  Desktop Client Settings:"
echo ""
echo "✅ Import .conf file or scan QR code"
echo "✅ Activate tunnel by clicking 'Activate'"
echo "✅ Check connection status shows 'Active'"
echo ""

echo "🔧 If VPN connects but no internet:"
echo ""
echo "1. Server side - run these scripts:"
echo "   sudo ./fix-routing.sh"
echo "   ./fix-vpn-internet.sh"
echo ""
echo "2. Client side - check:"
echo "   - AllowedIPs = 0.0.0.0/0"
echo "   - DNS settings are present"
echo "   - No other VPN running"
echo "   - Firewall allows WireGuard"
echo ""

echo "🌐 Server Info:"
echo "   Public IP: $PUBLIC_IP"
echo "   WireGuard Port: 51820"
echo "   Web Interface: https://wg.buq.duckdns.org"
echo ""

echo "📞 Still having issues?"
echo "   1. Check server logs: docker logs wg-easy"
echo "   2. Check server routing: ./fix-vpn-internet.sh"
echo "   3. Verify firewall: sudo ufw status"
echo "   4. Test direct connection: telnet $PUBLIC_IP 51820"
