http:
  middlewares:
    services:
      basicAuth:
        users:
          - 'admin:$2y$05$NZX8hLOO3h0T8TqFOqzgJeGz/SLnLVKEvosWt5vi5vsoBl/5H.vsy'  # admin:Arema123
    compress:
      compress: {}
    hsts:
      headers:
        stsSeconds: 2592000
  routers:
    api:
      rule: Host(`traefik.buq.duckdns.org`)
      entrypoints:
        - websecure
      middlewares:
        - services
      service: api@internal

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      sniStrict: true
